Maselkov/GW2Bot

- guildwars2/api.py
- guildwars2/characters.py
- guildwars2/commerce.py
- guildwars2/guild/general.py
Added $guild set and $guild unset to store preferred Guild in database 
If guild is set, other guild commands (like treasury or info) can be invoked without explicitly typing the guild name again
> Preferred guild setting

- guildwars2/guild/sync.py
Add `$guildsync guildrole on/off`. 
- Creates a new role based off the name of the guild when toggled on.
- Adds the guild role to the list of allowed ranks.
- Adds all members with an in-game rank to the umbrella guild role.
- Forces a guild sync when toggled off to delete the role.
> $guildsync guildrole toggle command

- guildwars2/account.py
- guildwars2/database.py
fixes #42 
api doesnt allow to search through upgrades in shared inventory slots. only if the upgrade changes the item id, so thats not included
> added search for upgrades in items

- guildwars2/account.py
- guildwars2/gamedata.json
Adds a command for checking which raid and fractal encounters were completed.
- The requirements are hardcoded, there is no way around that as far as I know.
- When more raids/fractals are added, they will have to be added.
- The layout isn't very pretty
- Double-check achievement ids
- Mention in README?
- Find amount of kill proof items in inventories (or spent in case of Shattered Observatory CM).
> Add a kill proof command

- guildwars2/gamedata.json
The achievement for defeating him without any spirits being consumed was used instead.
> Use correct achievement for Gorseval in kill proof

- guildwars2/misc.py
Add the german, french and spanish wikis to the wiki command to allow players that don't know the english names to search in their language.
Languages are chosen by appending the language tag (en, de, fr, es) to the search command.
If no language is given it defaults to english so that the current usage stays unchanged.
> Add localized versions for the wiki command

- guildwars2/gamedata.json
Names will have to be updated to be the same as in the API when the new raid is added to it. If that ever happens.
I didn't have a chance to test this locally as gw2bot doesn't want to run. I did double-check the ids.
> Add Mythwright Gambit achievements to the killproof command

- guildwars2/gamedata.json
Adds The Key of Ahdashim raid to the killproof command. The new section includes
- Adina
- Adina CM
- Sabir
- Sabir CM
- Qadim the Peerless
- Qadim the Peerless CM
The order chosen (as the two first bosses can be done in any order) matches the order specified in the official API.
> Add Wing 7 achievements for the killproof command

- guildwars2/wallet.py
- Renamed get_ls_currencies as it doesnt only search for ls items now
- Added regex to remove numbers from name, because provisioner tokens are named "1 Provisioner Token" in api
> Added provisioner tokens to maps section

- guildwars2/account.py
- guildwars2/gamedata.json
Very similar to the `$cats` command, this command tells the user the home instance nodes that haven't been collected yet.
> Added a nodes command

- guildwars2/gamedata.json
This adds the OLC strikes to the /kp command by updating the gamedata.json file.
The three achievements for OLC included are:
* Old Lion's Court, Achievement ID: 6797
* Old Lion's Court CM, Achievement ID: 6804
* Old Lion's Court: Fear Not This Knight, Achievement ID: 6778
Link to the GW2 API with the achievement IDs: https://api.guildwars2.com/v2/achievements?ids=6797,6804,6778
> Add OLC Strikes to KP command

- guildwars2/gamedata.json
Added icons and data for missing boss encounters:
- Ai, Keeper of the Peak (Sunqua Peak),
- Legendary Icebrood Construct (Shiverpeaks Pass),
- Voice of the Fallen and Claw of the Fallen,
- Fraenir of Jormag,
- Boneskinner,
- Whisper of Jormag,
- Captain Mai Trin & Echo Of Scarlet Briar (Aetherblade Hideout),
- Ankka (Xunlai Jade Junkyard),
- Minister Li (Kaineng Overlook),
- The Dragonvoid (Harvest Temple),
- Watchknight Triumvirate (Old Lion's Court),
- Freezie (Secret Lair of the Snowmen)
> Added missing bosses to gamedata.json

- LICENSE
Changed to [GNU GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) to reflect what is stated in the ToS & Privacy Policy on the website.
Btw it seems like you must remove the existing `LICENSE` file first and then add this one. See [here](https://github.com/orgs/community/discussions/23555). Note this change in license does not effect previous versions or forks of GW2Bot; only new changes added hereafter.
> MIT -> GNU GPL

- guildwars2/daily.py
- guildwars2/gamedata.json
This adds the EoD Priority Strike to the `/daily` command. It follows the same pattern as IBS daily strikes, and adds the list of strikes to the JSON data and then uses an index based on today's date.
We could probably update this to use the GW2 API, as there is now an achievement category endpoint that [returns the IDs of the current strikes](https://api.guildwars2.com/v2/achievements/categories/250). Doing so would be future-proof to other strike additions. I didn't have the time at the moment, but I may do another PR in the future to make that update 😄
> Adds EoD Priority Strike to the /daily command

- guildwars2/gamedata.json
This includes two changes:
* Updates the Fractal Scales for the Daily Recommended Fractal, including the addition of the new Silent Surf Fractal.
* Adds the Fractal CM Title Achievements to the `/kp` command, which is often asked for in NA groups.
> Updates Fractal Scales and adds Fractal CM Titles to KP

- guildwars2/notifiers.py
- requirements.txt
The basic idea is as follows: 
1. Check the RSS feed for the latest post
2. Retrieve HTML source for that post from forum
3. Do some regex and markdown parsing magic to get the patch notes out of that.
4. Keep track in the database of number of already sent out messages per forum post.
5. If amount of comments in the latest post exceeds the amount stored in the database, send out the new ones.
Worked in my test instance, but better test it by yourself first. The 4 latest patch notes might be pushed out on startup since the database is not populated.
Use for example the following mongosh line to test the behaviour. Alter the count value to emulate the behavior of new posts.
`db.gw2.updates.updateOne({"title": 'Game Update Notes: July 18, 2023'}, { "$set": {"title": 'Game Update Notes: July …
> New GW2 updater handling

- guildwars2/gamedata.json
This adds the Silent Surf CM and CM title to the `/kp` command.
Achievement IDs can be seen here: https://api.guildwars2.com/v2/achievements?ids=6938,6950
> Add Silent Surf CM achievements to KP

- guildwars2/gamedata.json
This adds the SoTo strikes (including new CO CM) to the `/kp` command.
Achievement IDs were verified on the GW2 API and command was run locally. Please see this link for the IDs: https://api.guildwars2.com/v2/achievements?ids=7163,7678,7116
* Cosmic Observatory: 7163
* Cosmic Observatory CM: 7678
* Temple of Febe: 7116
> Add Soto Strikes to kp command

- guildwars2/gamedata.json
Added boss IDs and icons to gamedata.json:
Kanaxai, Scythe of House Aurkus (Silent Surf Fractal): 25572 normal mode
25577 challenge mode
Dagda (Cosmic Observatory Strike Mission):
25705
Cerus (Temple of Febe Strike Mission):
25989
Also changed "Siax the Corrupted" to just "Siax" to be less specific, because the normal mode and challenge mode bosses share the same ID but have different suffixes.
Also changed the icon for WvW encounters to Chest of the Mists icon for better visibility at small size.
> Updated gamedata.json

- guildwars2/gamedata.json
Public convergences seem to be the only event on a 3-hour cycle.
I'm not sure if the first event occurs at 00:30 or 01:30 bot time.
Also I don't know if the 3-hour event cycle might break the bot somehow.
[Convergences in gamedata.json](https://github.com/Maselkov/GW2Bot/pull/151/files#diff-f96035da98fe067745b2ca27cedf28692180996fff0ea8927c8710a46528a538R940-R956)
> Added SoTO event timers to gamedata.json

- guildwars2/account.py
Fixes #158
I tried to test this on my personal server but I couldn't get the bot to respond to my DM's to load the GW2Bot cog.
> fix: PathOfFire implies HeartOfThorns access
